[dnssec] Fix ASN.1 encoding if DSA signatures
Starting with JDK 8u121 the Java became more strict about DER
encoding. The particular case we are hitting here are leading zeros in
ASN.1 DER integer encoding, which will be rejected in Java 8u121. See

https://bugs.openjdk.java.net/browse/JDK-8174719
and
http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/rev/31dae74ad077#l5.16

Fixes

DsaSingatureVerifierTest > testDSAWrongSignature() FAILED
    org.minidns.dnssec.DnssecValidationFailedException: Validating signature failed
        at org.minidns.dnssec.algorithms.JavaSecSignatureVerifier.verify(JavaSecSignatureVerifier.java:55)
        at org.minidns.dnssec.algorithms.SignatureVerifierTest.verify(SignatureVerifierTest.java:54)
        at org.minidns.dnssec.algorithms.SignatureVerifierTest.assertSignatureInvalid(SignatureVerifierTest.java:46)
        at org.minidns.dnssec.algorithms.DsaSingatureVerifierTest.testDSAWrongSignature(DsaSingatureVerifierTest.java:56)

        Caused by:
        java.security.SignatureException: Invalid encoding for signature
            at java.base/sun.security.provider.DSA.engineVerify(DSA.java:346)
            at java.base/sun.security.provider.DSA.engineVerify(DSA.java:292)
            at java.base/java.security.Signature$Delegate.engineVerify(Signature.java:1416)
            at java.base/java.security.Signature.verify(Signature.java:790)
            at org.minidns.dnssec.algorithms.JavaSecSignatureVerifier.verify(JavaSecSignatureVerifier.java:50)
            ... 3 more

            Caused by:
            java.io.IOException: Invalid encoding: redundant leading 0s
                at java.base/sun.security.util.DerInputBuffer.getBigInteger(DerInputBuffer.java:161)
                at java.base/sun.security.util.DerValue.getBigInteger(DerValue.java:545)
                at java.base/sun.security.provider.DSA.engineVerify(DSA.java:344)
                ... 7 more